on:
  push:
    branches:
      - main
jobs:
  render_keymap:
    name: Render Keymap
    runs-on: ubuntu-22.04
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # changed files to the repository.
      contents: write
    
    steps:
      - name: Install Dependencies
        run: pip install keymap-drawer
      - name: Clone Repo
        uses: actions/checkout@v4
      - name: Render Keymap
        run: bash ./bin/render.sh
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto-render keymap"
